[package]
name = "split_bgi"
version = "0.1.0"
authors = ["Peter van Heusden <pvh@sanbi.ac.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "0.2.1"
bio = "0.28.2"
clap = "2.33.0"